server:
  port: 3000.0
spring:
  application:
    name: board-service
    version: v1
    desc: board-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  datasource:
    dbcp2:
      initial-size: 20
    url: jdbc:mariadb://${MARIA_DB_HOST:127.0.0.1}:${MARIA_DB_PORT:3306}/${MARIA_DB_NAME:test}?createDatabaseIfNotExist=true&allowMultiQueries=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${MARIA_DB_USERNAME:root}
    password: ${MARIA_DB_PASSWORD:0000}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        storage_engine: innodb
        format_sql: true
        default_batch_fetch_size: 1000
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-mariadb.sql
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info
info:
  app:
    name: Board Service
    description: 게시판관리, 게시물관리, 첨부파일관리 기능을 제공
file:
  directory: ${user.home}/msa-attach-volume
messages:
  directory: ${file.directory}/messages
token:
  secret: token_secret
ftp:
  enabled: false
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@${eureka.instance.hostname:localhost}:8761/eureka
service-path: ${SERVICE_PATH:}/board-service
